development:
  host: localhost
  database: pivot_it_development

test:
  host: localhost
  database: pivot_it_test

# set these environment variables on your prod server
production:
  uri: mongodb://heroku:256ee0f372f7b6d6b4d4d4e4e4dcf0d9@flame.mongohq.com:27064/app3716188
# production:
  # host: <%= ENV['MONGOID_HOST'] %>
  # port: <%= ENV['MONGOID_PORT'] %>
  # username: <%= ENV['MONGOID_USERNAME'] %>
  # password: <%= ENV['MONGOID_PASSWORD'] %>
  # database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
